apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-ping
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-ping
rules:
- apiGroups:
    - ""
    - apps
  resources:
    - pods
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-ping
subjects:
  - kind: ServiceAccount
    namespace: default
    name: k8s-ping
roleRef:
  kind: ClusterRole
  name: k8s-ping
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ping
spec:
  selector:
    matchLabels:
      app: k8s-ping
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-ping
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - k8s-ping
                topologyKey: kubernetes.io/hostname
      containers:
        - name: k8s-ping
          command: ["k8s-ping", "-d", "1000", "-n", "default"]
          image: ghcr.io/kentik/k8s-ping
          imagePullPolicy: Always
      serviceAccount: k8s-ping
---
