name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.0
        with:
          targets: x86_64-unknown-linux-musl
          toolchain: stable
      - run: |
          cargo build --release
          cp target/release/k8s-ping .
        shell: bash
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/kentik/k8s-ping
          push: true
          context: .
